export type BusinessErrorCode =
  | "PRINTER_NAME_REQUIRED"
  | "PRINTER_NAME_ALREADY_EXISTS"
  | "PRINTER_INVALID_STATUS"
  | "PRINTER_NOT_FOUND"
  | "PRINTER_IN_MAINTENANCE"
  | "PRINTER_ALREADY_PRINTING"
  | "PRINTER_HAS_ACTIVE_PRINT"
  | "PRINTER_INACTIVE"
  | "PRINTER_INVALID_IP"
  | "PRINTER_MODEL_INVALID"
  | "PRINTER_LOCATION_INVALID"
  | "ORDER_CODE_REQUIRED"
  | "ORDER_CODE_ALREADY_EXISTS"
  | "ORDER_INVALID_STATUS"
  | "ORDER_NOT_FOUND"
  | "ORDER_ALREADY_DELIVERED"
  | "ORDER_ALREADY_CANCELLED"
  | "ORDER_INACTIVE"
  | "ORDER_PRINT_ALREADY_LINKED"
  | "ORDER_PRINT_NOT_FOUND"
  | "ORDER_PRINT_LINK_NOT_FOUND"
  | "ORDER_CANNOT_BE_DELIVERED_UNLESS_READY"
  | "ORDER_CANNOT_BE_DELETED_WHEN_DELIVERED"
  | "ORDER_CUSTOMER_NAME_INVALID"
  | "ORDER_OBSERVATIONS_INVALID"
  | "ORDER_ESTIMATED_DELIVERY_DATE_INVALID"
  | "ORDER_PRINT_JOB_ID_REQUIRED"
  | "PRINT_JOB_NOT_FOUND"
  | "PRINT_JOB_MODEL_NAME_REQUIRED"
  | "PRINT_JOB_MODEL_FIELD_INVALID"
  | "PRINT_JOB_ESTIMATED_DURATION_INVALID"
  | "PRINT_JOB_OBSERVATIONS_INVALID"
  | "PRINT_JOB_ORDER_ID_REQUIRED"
  | "PRINT_JOB_ORDER_NOT_AVAILABLE"
  | "PRINT_JOB_INVALID_STATUS"
  | "PRINT_JOB_INACTIVE"
  | "PRINT_JOB_CANNOT_BE_CHANGED"
  | "PRINT_JOB_CANNOT_BE_ASSIGNED"
  | "PRINT_JOB_CANNOT_BE_CANCELLED"
  | "PRINT_JOB_CANNOT_BE_FINISHED"
  | "PRINT_JOB_CANNOT_BE_DELETED_WHEN_RUNNING"
  | "ASSIGNMENT_INVALID_STRATEGY"
  | "ASSIGNMENT_DURATION_REQUIRED"
  | "ASSIGNMENT_DURATION_INVALID"
  | "ASSIGNMENT_ORDER_LENGTH_FILTER_REQUIRED"
  | "ASSIGNMENT_ORDER_LENGTH_INVALID"
  | "STATISTICS_INVALID_DATE_RANGE";

export class BusinessError extends Error {
  constructor(
    public readonly code: BusinessErrorCode,
    message: string = code
  ) {
    super(message);
    this.name = "BusinessError";
  }
}
